import type { Evento } from "./types"

// Todos los eventos del archivo HTML original (36 eventos)
export const EVENTOS_COMPLETOS: Omit<Evento, "id" | "createdAt" | "updatedAt">[] = [
  // === MAYO ===
  { nombre: "MAYO 1° Bo BELGRANO FERIA+CLUB+CENTENARIO", fecha: "2026-05-01", horario: "10.30 a 22 aprox", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-2690-272", contacto: "3751663071", sonido: "CULTURA", viandas: "SI", sillas: "100", mesas: "", gazebos: "20", tarimas: "2", gradas: "", banos: "4", luces: "", luminarias: "KERMES", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "CINTAS" },
  { nombre: "MAYO 1 VIERNES - Bo 1° DE MAYO ANIV", fecha: "2026-05-01", horario: "", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "", contacto: "3751506246", sonido: "OTRO", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "CONFIRMADO", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 2 - LOS CEDROS", fecha: "2026-05-02", horario: "", estado: "LISTO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "", contacto: "3751521171", sonido: "OTRO", viandas: "NO", sillas: "", mesas: "4", gazebos: "", tarimas: "", gradas: "", banos: "6", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 4 - 20 ANIVERSARIO HOGAR BETANIA", fecha: "2026-05-04", horario: "10.30 a 12", estado: "LISTO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "", contacto: "3751669873", sonido: "CULTURA", viandas: "NO", sillas: "50", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 6 - DIR NIÑEZ TALLER", fecha: "2026-05-06", horario: "", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "", contacto: "LETTY LOPEZ", sonido: "SIN", viandas: "NO", sillas: "30", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 7 - PLZA SARMIENTO ZOONOSIS", fecha: "2026-05-07", horario: "", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "", contacto: "MATI MONTI", sonido: "SIN", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 8 - CIC PINARES DIR NIÑEZ", fecha: "2026-05-08", horario: "16 a 19", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "", contacto: "LETICIA LOPEZ", sonido: "CULTURA", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "Y BIBLIOTECA MOVIL", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 8 - 170 ANIV POLICIA DE MISIONES", fecha: "2026-05-08", horario: "600.000 sec gob", estado: "LISTO", prioridad: "ALTA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "", contacto: "3751477260", sonido: "MK", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "PEDIDO +PALCOS", banos: "", luces: "", luminarias: "", transito: "VER CORTE", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "PEDIR COSTANERA", autExpendio: "", planeta: "" },
  { nombre: "MAYO 9 - VIRGEN DE LUJAN CAPILLA", fecha: "2026-05-09", horario: "", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-3344-297", contacto: "3751571383", sonido: "SIN", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "SIN DISPONIBILIDAD", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 9 - FERIA SOCIAL + FIESTA REVIRO", fecha: "2026-05-09", horario: "sec gob (costo c/ policia)", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "", contacto: "ROLANDO VERGARA", sonido: "MK", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 10 - Bo ESPERANZA FERIA", fecha: "2026-05-10", horario: "de 15 a 17 hs", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "se paso al 17/5/26", contacto: "3751571383", sonido: "SIN", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 10 - APERTURA INFANTO JUVENIL", fecha: "2026-05-10", horario: "9 a", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "IV-3303-295", contacto: "3751501987", sonido: "CULTURA", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 16 - PLAZA KM 6 FERIA", fecha: "2026-05-16", horario: "", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-3296-295", contacto: "3751343114", sonido: "SIN", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "2", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 15 y 16 - PERICON NACIONAL POLI KM 9", fecha: "2026-05-16", horario: "domingo 8 a 18", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "", registro: "", contacto: "FAUSTO", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "100", mesas: "", gazebos: "", tarimas: "4", gradas: "", banos: "", luces: "PANTALLAS FRIGOLA", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 17 - Bo LOS LAPACHOS DUATLON", fecha: "2026-05-17", horario: "", estado: "SUSPENDIDO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "", registro: "IV-2678-272", contacto: "3751359.29", sonido: "SIN", viandas: "NO", sillas: "50", mesas: "3", gazebos: "", tarimas: "", gradas: "", banos: "2", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 17 DOMINGO - JINETEADA - BHAR", fecha: "2026-05-17", horario: "", estado: "LISTO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "", registro: "", contacto: "3751376695", sonido: "OTRO", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 19 - ENTREGA BECAS ESTUDIANTILES", fecha: "2026-05-19", horario: "10 a 12.30", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "V-3562-006", contacto: "CINTIA TALAVERA", sonido: "CULTURA", viandas: "NO", sillas: "100", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 20 - CONCIENTIZACION ESTRELLAS AMARILLAS", fecha: "2026-05-20", horario: "horario laboral", estado: "LISTO", prioridad: "ALTA", ambito: "EXTERNO", traslado: "SIN NOTA", registro: "", contacto: "", sonido: "CULTURA", viandas: "", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 21 - DIA BANDERA DIVINO NIÑO", fecha: "2026-05-21", horario: "horario laboral", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "SIN NOTA", registro: "PROTOCOLO", contacto: "", sonido: "CULTURA", viandas: "", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 22 - DIR NIÑEZ EVENTO INFORMATIVO SUM", fecha: "2026-05-22", horario: "9.30 A 13", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "", contacto: "LETICA LOPEZ", sonido: "CULTURA", viandas: "NO", sillas: "30", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "A espera de ingreso nota", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 23 Y 24 - CIRCUITO GONSESKI", fecha: "2026-05-23", horario: "800", estado: "LISTO", prioridad: "ALTA", ambito: "EXTERNO", traslado: "", registro: "", contacto: "JUAN CRUZ", sonido: "ALDO", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "3", gradas: "PEDIDO", banos: "", luces: "", luminarias: "", transito: "PEDIR POLICIA", ambulancia: "ACCION SOCIAL", contingencia: "", ambiente: "TRAMITADO", autMunicipal: "", autCde: "TRAMITADO", autExpendio: "", planeta: "" },
  { nombre: "MAYO 23 - PLZA SARMIENTO HILVANANDO SUEÑOS", fecha: "2026-05-23", horario: "20 a 23", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-2737-274", contacto: "3751414485", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "100", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "VER", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "TRAMITADO", autExpendio: "", planeta: "" },
  { nombre: "MAYO 25 - ACTO ESC 202", fecha: "2026-05-25", horario: "8 a 11.30", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "SIN NOTA", registro: "PROTOCOLO", contacto: "PROTOCOLO", sonido: "CULTURA", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 25 - JUEGO DE RIENDAS SOMRAU", fecha: "2026-05-25", horario: "820", estado: "LISTO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-3288-295", contacto: "3751666566", sonido: "SILVERO HORACIO", viandas: "VER", sillas: "", mesas: "", gazebos: "", tarimas: "4", gradas: "", banos: "4", luces: "GRUPO", luminarias: "CHEQUEAR EL LUGAR", transito: "", ambulancia: "ACCION SOCIAL", contingencia: "", ambiente: "", autMunicipal: "PEDIDO", autCde: "", autExpendio: "PEDIDO", planeta: "" },
  { nombre: "MAYO 28 - CIRCULO MEDICO CONGRESO PREVENCION", fecha: "2026-05-28", horario: "7 a 13", estado: "LISTO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "V-3481-003", contacto: "VANESA MOESCH", sonido: "CULTURA", viandas: "NO - 8 hs", sillas: "ORNAMENTACION ESCENARIO", mesas: "3", gazebos: "", tarimas: "4", gradas: "", banos: "", luces: "PROYECTOR", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 28 - NENI 2086 EN LA INSTITUCION", fecha: "2026-05-28", horario: "", estado: "GESTIONANDO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "V-3799-017", contacto: "3751448959", sonido: "VER", viandas: "NO", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "PEDIDO", luminarias: "", transito: "PEDIDO", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 29 - CAPACITACION RCP TERMINAL RRHH", fecha: "2026-05-29", horario: "9 a 17", estado: "GESTIONANDO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "V-3857-020", contacto: "PATRICIA KLANNER", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "DOS COMISIONES", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "MAYO 29-31 - FECHA AUTOMOVILISMO AUTODROMO", fecha: "2026-05-29", horario: "8 a 16", estado: "GESTIONANDO", prioridad: "ALTA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "V-3852-020", contacto: "MICHI MOSCHNER", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "", mesas: "30", gazebos: "", tarimas: "VER", gradas: "", banos: "", luces: "", luminarias: "", transito: "VER", ambulancia: "ACCION SOCIAL", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "VER", planeta: "" },
  // === JUNIO ===
  { nombre: "JUNIO 2 - CONCURSO AMBIENTE POLI KM 9", fecha: "2026-06-02", horario: "7.30 a 12.30", estado: "GESTIONANDO", prioridad: "ALTA", ambito: "INSTITUCIONAL", traslado: "TRASLADO", registro: "29/4/26 SEC GOB", contacto: "VALERIA SCHENDELBECK", sonido: "CULTURA", viandas: "NO", sillas: "100", mesas: "3", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "PANTALLA - FRIGOLA 250.000", luminarias: "", transito: "", ambulancia: "APS MUNICIPAL", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "JUNIO 13 - Bo MALVINAS", fecha: "2026-06-13", horario: "20 A 24/24.30 HS", estado: "GESTIONANDO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "", registro: "IV-2422-262", contacto: "3751619155", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "", mesas: "VER", gazebos: "6", tarimas: "4", gradas: "", banos: "4", luces: "GRUPO", luminarias: "VER TABLERO CEEL", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "DEBE PEDIR", autExpendio: "", planeta: "" },
  { nombre: "JUNIO 20 - Bo 20 DE JUNIO ANIVERSARIO", fecha: "2026-06-20", horario: "", estado: "AGENDADO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "", registro: "IV-3180-291", contacto: "3751353678", sonido: "CULTURA", viandas: "VER", sillas: "50", mesas: "25", gazebos: "12", tarimas: "4", gradas: "", banos: "5", luces: "GRUPO", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  // === JULIO ===
  { nombre: "JULIO 4 - ATREM DIA DEL LOCUTOR TEMBIU PORA", fecha: "2026-07-04", horario: "", estado: "AGENDADO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "", registro: "IV-2946-282", contacto: "ALCIDESAGUINAGALDE", sonido: "VER", viandas: "NO - 8 hs", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  { nombre: "JULIO 11 Y 12 - ELDORADO SALVAJE", fecha: "2026-07-12", horario: "", estado: "AGENDADO", prioridad: "ALTA", ambito: "EXTERNO", traslado: "", registro: "", contacto: "SANDRA ROLON", sonido: "VER", viandas: "SI + 8 HS", sillas: "", mesas: "10", gazebos: "12", tarimas: "", gradas: "", banos: "4", luces: "MEDALLAS CON ROBOTICA", luminarias: "", transito: "VER SEGUN PLANO DE CORTE", ambulancia: "ACCION SOCIAL C/ENFERMERA", contingencia: "VER C/ MARIO EN BASE A PLANOS", ambiente: "", autMunicipal: "DEBEN TRAMITAR", autCde: "", autExpendio: "", planeta: "" },
  // === AGOSTO ===
  { nombre: "AGOSTO 16 - Bo PORVENIR DIA DEL NIÑO", fecha: "2026-08-16", horario: "", estado: "GESTIONANDO", prioridad: "MEDIA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-3222-292", contacto: "3751444343", sonido: "SIN", viandas: "NO - 8 hs", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "A PARTIR 15.30 HS", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  // === NOVIEMBRE ===
  { nombre: "NOVIEMBRE 6 - EFA FIESTA DE LA TRADICION", fecha: "2026-11-06", horario: "18 a 23", estado: "GESTIONANDO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "TRASLADO", registro: "IV-3027-285", contacto: "3751403xxx", sonido: "CULTURA", viandas: "VER", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "GRUPO", luminarias: "KERMES", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
  // === DICIEMBRE ===
  { nombre: "DICIEMBRE 9 - ACTO COLACION EPET 54", fecha: "2026-12-09", horario: "19 a", estado: "GESTIONANDO", prioridad: "BAJA", ambito: "EXTERNO", traslado: "", registro: "IV-2288-256", contacto: "375148-148", sonido: "CULTURA", viandas: "SI + 8 HS", sillas: "", mesas: "", gazebos: "", tarimas: "", gradas: "", banos: "", luces: "", luminarias: "", transito: "", ambulancia: "", contingencia: "", ambiente: "", autMunicipal: "", autCde: "", autExpendio: "", planeta: "" },
]
